dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - ruby-head
before_install:
  - gem install bundler -v 1.16.1
  - npm install -g puppeteer
  - npm install
  - unset _JAVA_OPTIONS
matrix:
  allow_failures:
    - rvm: ruby-head

